# Backend Dockerfile
FROM python:3.11-slim
WORKDIR /app

# зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# папкa для загрузок
RUN mkdir -p uploads
# Открываем порт
EXPOSE 8000
# Запускаем сервер
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]